Cloud hosted guide adjustments
OpenLiberty/guide-docker pull request #120
Opened 2021-06-09 19:59 UTC by AustinSeto

2021-06-16 19:31 UTC, rutavshah reviewed
Tested and passed on cloud hosted environment and statically.

2021-06-18 20:06 UTC, rutavshah approved these changes
Tested on cloud hosted environment and passed

2021-06-18 20:22 UTC, dmuelle requested changes
a few edits suggestions

2021-06-18 20:22 UTC, dmuelle commented on README.adoc
> +Before you begin, Docker needs to be installed.
Before you begin, you need to install Docker if it is not already installed.

2021-06-18 20:22 UTC, dmuelle commented on README.adoc
> +You can write tests for the individual units of code outside of a running application server,
or they can be written to call the application server directly.
--->
or you can write them to call the application server directly.

2021-06-18 20:22 UTC, dmuelle commented on README.adoc
> +or they can be written to call the application server directly.
see previous comment

2021-06-18 20:22 UTC, dmuelle commented on README.adoc
> +You have just iteratively developed a simple REST application in a container with Open Liberty and Docker.
You have just
--->
You just

2021-06-22 15:57 UTC, AustinSeto commented
Thank you @dmuelle, all suggested changes made

2021-06-25 17:00 UTC, dmuelle approved these changes
LGTM

2021-07-13 14:39 UTC, merged